version: 2
jobs:
  verify-code:
    docker:
      - image: starefossen/node-imagemagick:4-6
    steps:
      - checkout
      - run:
           name: echo nodejs information
           command: |
             echo "node version $(node -v) running"
             echo "npm version $(npm -v) running"
      - run:
          name: install-lint-test
          command: |
            npm install
            npm run lint
            npm test
          environment:
            AWS_BUCKET_NAME: jotunheimr
            AWS_BUCKET_PATH: k8s_test/
            AWS_BUCKET_REGION: eu-west-1

      - run:
          name: npm coverage
          command: |
            npm run cover
            cat ./coverage/lcov.info | npm run codacy-coverage

      - run:
          name: npm project security
          command: |
            npm run nsp

      - run:
           name: notify slack on failure
           when: on_fail
           command: |
             chmod +x .circleci/notify-slack.sh
             ./.circleci/notify-slack.sh Jotunheimr build-publish-deploy false

      - run:
           name: notify slack on sucess
           when: on_success
           command: |
             chmod +x .circleci/notify-slack.sh
             ./.circleci/notify-slack.sh Jotunheimr build-publish-deploy true


  build-image:
    docker:
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - run:
          name: authenticate with gcloud
          command: |
            echo $GCLOUD_DOCKER_CREDENTIALS > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      # if authentication succeeded - checkout code
      - checkout

      # starts a remote docker environment to run docker commands
      - setup_remote_docker

      - run:
          name: build Jotunheimr docker image and push image to GCR
          command: |
            gcloud auth configure-docker --quiet
            TAG=${CIRCLE_SHA1:0:9}
            docker build -t jotunheimr .
            docker tag jotunheimr eu.gcr.io/dnt-docker-registry-public/jotunheimr:latest
            docker tag jotunheimr eu.gcr.io/dnt-docker-registry-public/jotunheimr:$TAG
            docker push eu.gcr.io/dnt-docker-registry-public/jotunheimr:latest
            docker push eu.gcr.io/dnt-docker-registry-public/jotunheimr:$TAG

      - run:
          name: notify slack on sucess
          when: on_success
          command: |
            chmod +x .circleci/notify-slack.sh
            ./.circleci/notify-slack.sh Jotunheimr build-publish-deploy true

      - run:
          name: notify slack on failure
          when: on_fail
          command: |
            chmod +x .circleci/notify-slack.sh
            ./.circleci/notify-slack.sh Jotunheimr build-publish-deploy false

  deploy-to-dev:
    docker:
      - image: praqma/helmsman:v1.3.0-helm-v2.8.1
    steps:
      - checkout
      - run:
          name: run helmsman
          command: |
            helmsman -debug -apply -f .circleci/helmsman-dev-deployment.toml
  deploy-to-beta:
    docker:
      - image: praqma/helmsman:v1.3.0-helm-v2.8.1
    steps:
      - checkout
      - run:
          name: run helmsman
          command: |
            helmsman -debug -apply -f .circleci/helmsman-beta-deployment.toml

  # deploy-to-prod:
  #   docker:
  #     - image: praqma/helmsman:v1.3.0-helm-v2.8.1
  #   steps:
  #     - checkout
  #     - run:
  #         name: run helmsman
  #         command: |
  #           helmsman -debug -apply -f .circleci/helmsman-prod-deployment.toml
workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - verify-code:
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only:
                - circleci
      - build-image:
          requires:
            - verify-code
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only:
                - circleci
      # - deploy-to-dev:
      #     requires:
      #       - build-image
      #     context: dnt-k8s-dev-beta
      #     filters:
      #       branches:
      #         only:
      #           - master
      # - deploy-to-beta:
      #     context: dnt-k8s-dev-beta
      #     filters:
      #       branches:
      #         only:
      #           - deploy-beta

      # - deploy-to-prod:
      #     context: dnt-k8s-prod
      #     filters:
      #       branches:
      #         only:
      #           - deploy-prod
